TeamDataForum/TeamDataForum.Web/Models/BindingModels/Forums/EditForumBindingModel.cs
namespace TeamDataForum.Web.Models.BindingModels.Forums
{
    using System.ComponentModel.DataAnnotations;
    using Resources;
    using Users;

    public class EditForumBindingModel
    {
        [Required]
        public int Id { get; set; }

        [Required(AllowEmptyStrings = false,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorForumTitleRequired),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [MaxLength(NumericValues.TextMaxLength,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorForumTitleMaxLength),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [Display(Name = "Forum title:")]
        [DataType(DataType.MultilineText)]
        public string Title { get; set; }

        [Required(AllowEmptyStrings = false,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorForumDescriptionRequired),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [MaxLength(NumericValues.TextMaxLength,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorForumDescriptionMaxLength),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [Display(Name = "Forum description:")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Required(
            ErrorMessageResourceName = nameof(ModelsRes.ErrorRequiredModerators),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [MinLength(1,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorNoModerators),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [Display(Name = "Forum moderators:")]
        public ModeratorBindingModel[] Moderators { get; set; }
    }
}

TeamDataForum/TeamDataForum.Web/Models/BindingModels/Forums/ForumBindingModel.cs
namespace TeamDataForum.Web.Models.BindingModels.Forums
{
    using System.ComponentModel.DataAnnotations;
    using Resources;
    using Users;

    public class ForumBindingModel
    {
        [Required(AllowEmptyStrings = false, 
            ErrorMessageResourceName = nameof(ModelsRes.ErrorForumTitleRequired),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [MaxLength(NumericValues.TextMaxLength,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorForumTitleMaxLength),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [Display(Name = "Forum title:")]
        [DataType(DataType.MultilineText)]
        public string Title { get; set; }

        [Required(AllowEmptyStrings = false,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorForumDescriptionRequired),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [MaxLength(NumericValues.TextMaxLength,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorForumDescriptionMaxLength),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [Display(Name = "Forum description:")]
        [DataType(DataType.MultilineText)]
        public string Description { get; set; }

        [Required(
            ErrorMessageResourceName = nameof(ModelsRes.ErrorRequiredModerators),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [MinLength(1,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorNoModerators),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [Display(Name = "Forum moderators:")]
        public ModeratorBindingModel[] Moderators { get; set; }
    }
}

TeamDataForum/TeamDataForum.Web/Models/BindingModels/Posts/EditPostBindingModel.cs
namespace TeamDataForum.Web.Models.BindingModels.Posts
{
    using System.ComponentModel.DataAnnotations;
    using Resources;
    using Threads;

    public class EditPostBindingModel
    {
        [Required]
        public int Id { get; set; }

        [Required(ErrorMessageResourceName = nameof(ModelsRes.ErrorNoThread),
            ErrorMessageResourceType = typeof(ModelsRes))]
        public IdentifiableThreadBindingModel Thread { get; set; }

        [Required(AllowEmptyStrings = false,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorPostTextTextRequired),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [MinLength(NumericValues.PostTextMinValue,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorPostTextMinValue),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [MaxLength(NumericValues.PostTextMaxValue,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorPostTextMaxValue),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Post text")]
        public string Text { get; set; }
    }
}

TeamDataForum/TeamDataForum.Web/Models/BindingModels/Posts/PostDeleteBindingModel.cs
namespace TeamDataForum.Web.Models.BindingModels.Posts
{
    using System.ComponentModel.DataAnnotations;
    using Resources;
    using Threads;

    public class PostDeleteBindingModel
    {
        [Required]
        public int Id { get; set; }

        public IdentifiableThreadBindingModel Thread { get; set; }

        public string Text { get; set; }
    }
}

TeamDataForum/TeamDataForum.Web/Models/BindingModels/Posts/ThreadPostBindingModel.cs
namespace TeamDataForum.Web.Models.BindingModels.Posts
{
    using System.ComponentModel.DataAnnotations;
    using Resources;
    using Threads;
    
    public class ThreadPostBindingModel
    {
        [Required(ErrorMessageResourceName = nameof(ModelsRes.ErrorNoThread),
            ErrorMessageResourceType = typeof(ModelsRes))]
        public IdentifiableThreadBindingModel Thread { get; set; }

        [Required(AllowEmptyStrings = false,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorPostTextTextRequired),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [MinLength(NumericValues.PostTextMinValue,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorPostTextMinValue),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [MaxLength(NumericValues.PostTextMaxValue,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorPostTextMaxValue),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [Display(Name = "Post text")]
        [DataType(DataType.MultilineText)]
        public string Text { get; set; }
    }
}

TeamDataForum/TeamDataForum.Web/Models/BindingModels/Threads/ThreadBindingModel.cs
namespace TeamDataForum.Web.Models.BindingModels.Threads
{
    using System.ComponentModel.DataAnnotations;
    using Forums;
    using Posts;
    using Resources;

    public class ThreadBindingModel
    {
        [Required(AllowEmptyStrings = false,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorThreadTitleRequired),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [MaxLength(NumericValues.TextMaxLength,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorThreadTitleMaxLength),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [MinLength(NumericValues.ThreadTitleMinLength,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorThreadTitleMinLength),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Thread title")]
        public string Title { get; set; }

        [Required(ErrorMessageResourceName = nameof(ModelsRes.ErrorThreadNoForum),
            ErrorMessageResourceType = typeof(ModelsRes))]
        public IdentifiableForumBindingModel Forum { get; set; }

        [Required(ErrorMessageResourceName = nameof(ModelsRes.ErrorThreadNoPost),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [MinLength(NumericValues.PostTextMinValue,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorPostTextMinValue),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [MaxLength(NumericValues.PostTextMaxValue,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorPostTextMaxValue),
            ErrorMessageResourceType = typeof(ModelsRes))]
        [Display(Name = "Post text")]
        [DataType(DataType.MultilineText)]
        public string Text { get; set; }
    }
}

TeamDataForum/TeamDataForum.Web/Models/BindingModels/Users/ModeratorBindingModel.cs
namespace TeamDataForum.Web.Models.BindingModels.Users
{
    using System.ComponentModel.DataAnnotations;
    using Resources;

    public class ModeratorBindingModel
    {
        [Required(AllowEmptyStrings = false,
            ErrorMessageResourceName = nameof(ModelsRes.ErrorModeratorIdRequired),
            ErrorMessageResourceType = typeof(ModelsRes))]
        public string Id { get; set; }

        public int Number { get; set; }

        public string Username { get; set; }

        public bool IsChecked { get; set; }
    }
}

TeamDataForum/TeamDataForum.Web/Controllers/ForumController.cs
namespace TeamDataForum.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Web;
    using System.Web.Mvc;
    using Microsoft.AspNet.Identity.EntityFramework;
    using Bases;
    using DBModels;
    using Models.BindingModels.Forums;
    using Models.BindingModels.Users;
    using UnitOfWork.Contracts;

    [Authorize]
    public class ForumController : ForumBaseController
    {
        public ForumController(IUnitOfWork unitOfWork)
            : base(unitOfWork)
        {
        }

        // GET: Forum
        [AllowAnonymous]
        public ActionResult Index()
        {
            return this.RedirectToAction("Home", "Home");
        }

        /// <summary>
        /// Empty create for creating forum
        /// </summary>
        /// <returns>View for creating forum</returns>
        [Authorize(Roles = "Administrator")]
        public ActionResult Create()
        {
            var role = this.GetRoleByName("Moderator");

            ForumBindingModel model = new ForumBindingModel();
            model.Moderators = this.GetUsersByRole(role.Id);

            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Create(ForumBindingModel model)
        {
            var role = this.GetRoleByName("Moderator");

            if (!this.ModelState.IsValid)
            {
                model.Moderators = this.GetUsersByRole(role.Id);

                return this.View(model);
            }

            var moderatorsIds = model.Moderators
                .Select(m => m.Id)
                .ToArray();

            var users = this.UnitOfWork
                .UserRepository
                .Select(
                u => u.UserName == this.User.Identity.Name ||
                (moderatorsIds.Contains(u.Id) && u.Roles.Any(r => r.RoleId == role.Id)));

            var creator = users.FirstOrDefault(u => u.UserName == this.User.Identity.Name);

            Forum forum = new Forum()
            {
                Title = model.Title,
                Description = model.Description,
                Date = DateTime.Now,
                Creator = creator
            };

            foreach (var user in users)
            {
                forum.Moderators.Add(user);
            }

            forum = this.UnitOfWork
                .ForumRepository
                .Add(forum);

            this.UnitOfWork.SaveChanges();

            return this.RedirectToAction("View", "Home", new { Id = forum.ForumId });
        }

        /// <summary>
        /// Edit action for forum
        /// </summary>
        /// <param name="id">forum id</param>
        /// <returns>View</returns>
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id)
        {
            Forum forum = this.GetForum(id);

            if (forum == default(Forum) || forum.IsDeleted)
            {
                return this.RedirectToAction("BadRequest", "Error");
            }

            var role = this.GetRoleByName("Moderator");

            var moderators = this.GetUsersByRole(role.Id);

            foreach (var moderator in moderators)
            {
                if (forum.Moderators.Any(m => m.Id == moderator.Id))
                {
                    moderator.IsChecked = true;
                }
            }

            EditForumBindingModel forumModel = new EditForumBindingModel()
            {
                Id = forum.ForumId,
                Title = forum.Title,
                Description = forum.Description,
                Moderators = moderators
            };

            return this.View(forumModel);
        }

        /// <summary>
        /// Action to edit Forum
        /// </summary>
        /// <param name="id">Forum id</param>
        /// <param name="model">EditForumBindingModel</param>
        /// <returns>Redirects</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Edit(int id, EditForumBindingModel model)
        {
            Forum editForum = this.GetForum(id);

            if (editForum == default(Forum) || editForum.IsDeleted || id != model.Id)
            {
                return this.RedirectToAction("BadRequest", "Error");
            }

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            var role = this.GetRoleByName("Moderator");

            var moderatorsIds = model.Moderators
                .Select(m => m.Id)
                .ToArray();

            var users = this.UnitOfWork
                .UserRepository
                .Select(u => moderatorsIds.Contains(u.Id) && u.Roles.Any(r => r.RoleId == role.Id));

            string[] addedModerators = editForum.Moderators
                .Select(u => u.UserName)
                .ToArray();

            foreach (string userName in addedModerators)
            {
                if (!users.Any(u => u.UserName == userName))
                {
                    editForum.Moderators.Remove(editForum.Moderators.First(u => u.UserName == userName));
                }
            }

            foreach (User user in users)
            {
                if (!editForum.Moderators.Any(u => u.UserName == user.UserName))
                {
                    editForum.Moderators.Add(user);
                }
            }

            editForum.Title = model.Title;
            editForum.Description = model.Description;

            editForum = this.UnitOfWork
                .ForumRepository
                .Update(editForum);

            this.UnitOfWork.SaveChanges();

            return this.RedirectToAction("View", "Home", new { Id = editForum.ForumId });
        }

        /// <summary>
        /// Delete action for forum
        /// </summary>
        /// <param name="id">Forum id</param>
        /// <returns>View</returns>
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id)
        {
            Forum forum = this.GetForumNoModerators(id);

            if (forum == default(Forum) || forum.IsDeleted)
            {
                return RedirectToAction("BadRequest", "Error");
            }

            DeleteForumBindingModel deleteForum = new DeleteForumBindingModel()
            {
                Id = forum.ForumId,
                Title = forum.Title,
                Description = forum.Description
            };

            return this.View(deleteForum);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public ActionResult Delete(int id, DeleteForumBindingModel model)
        {
            Forum deleteForum = this.GetForumNoModerators(id);

            if (deleteForum == default(Forum) || deleteForum.IsDeleted || id != model.Id)
            {
                return this.RedirectToAction("BadRequest", "Error");
            }

            deleteForum.IsDeleted = true;

            this.UnitOfWork
                .ForumRepository
                .Update(deleteForum);

            this.UnitOfWork.SaveChanges();

            return this.RedirectToAction("Home", "Home");
        }

        private Forum GetForum(int id)
        {
            Forum forum = this.UnitOfWork
                .ForumRepository
                .Find(id, new string[] { "Moderators" });

            return forum;
        }

        private Forum GetForumNoModerators(int id)
        {
            Forum forum = this.UnitOfWork
                .ForumRepository
                .Find(id);

            return forum;
        }

        private ModeratorBindingModel[] GetUsersByRole(string roleId)
        {
            var users = this.UnitOfWork
                .UserRepository
                .Select(u => u.Roles.Any(r => r.RoleId == roleId));

            var moderators = new ModeratorBindingModel[users.Count];

            int counter = 0;

            for (int i = 0; i < users.Count; i++)
            {
                moderators[i] = new ModeratorBindingModel()
                {
                    Id = users[i].Id,
                    Number = counter++,
                    Username = users[i].UserName
                };
            }

            return moderators;
        }

        private IdentityRole GetRoleByName(string roleType)
        {
            var role = this.RoleManager
                .Roles
                .FirstOrDefault(r => r.Name == roleType);

            return role;
        }
    }
}

TeamDataForum/TeamDataForum.Web/Views/Shared/EditorTemplates/EditForumBindingModel.cshtml
@using TeamDataForum.Web.Models.BindingModels.Forums
@model EditForumBindingModel

@using (Html.BeginForm("Edit", "Forum", FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)
    @Html.DisplayFor(m => m.Title)
    @Html.EditorFor(m => m.Title)
    @Html.ValidationMessageFor(m => m.Title)
    @Html.DisplayFor(m => m.Description)
    @Html.EditorFor(m => m.Description)
    @Html.ValidationMessageFor(m => m.Description)
    @Html.EditorFor(m => m.Moderators)
    @Html.ValidationMessageFor(m => m.Id)
    @Html.AntiForgeryToken()
    <input type="submit" value="Edit" />
}

TeamDataForum/TeamDataForum.Web/Views/Shared/EditorTemplates/EditPostBindingModel.cshtml
@using TeamDataForum.Web.Models.BindingModels.Posts
@model EditPostBindingModel

@using (Html.BeginForm("Edit", "Post", FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)
    @Html.EditorFor(m => m.Thread)
    @Html.ValidationMessageFor(m => m.Thread)
    @Html.EditorFor(m => m.Post)
    @Html.ValidationMessageFor(m => m.Post)
    @Html.AntiForgeryToken()
    <input type="submit" value="Create" />
}

TeamDataForum/TeamDataForum.Web/Views/Shared/EditorTemplates/ForumBindingModel.cshtml
@using TeamDataForum.Web.Models.BindingModels.Forums
@model ForumBindingModel

@using (Html.BeginForm("Create", "Forum", FormMethod.Post))
{
    @Html.LabelFor(m => m.Title)
    @Html.EditorFor(m => m.Title)
    @Html.ValidationMessageFor(m => m.Title)
    @Html.LabelFor(m => m.Description)
    @Html.EditorFor(m => m.Description)
    @Html.ValidationMessageFor(m => m.Description)
    @Html.LabelFor(m => m.Moderators)
    @Html.EditorFor(m => m.Moderators)
    @Html.ValidationMessageFor(m => m.Moderators)
    @Html.AntiForgeryToken()
    <input type="submit" value="Create" />
}

TeamDataForum/TeamDataForum.Web/Views/Shared/EditorTemplates/ModeratorBindingModel.cshtml
@using TeamDataForum.Web.Models.BindingModels.Users
@model ModeratorBindingModel

<div>@Model.Username</div>
<input type="checkbox" name="Moderators[@Model.Number].Id" value="@Model.Id" checked="@Model.IsChecked" />
@Html.ValidationMessageFor(m => m.Id)

TeamDataForum/TeamDataForum.Web/Views/Shared/EditorTemplates/PostDeleteBindingModel.cshtml
@using TeamDataForum.Web.Models.BindingModels.Posts
@model PostDeleteBindingModel

@using (Html.BeginForm("Delete", "Post", FormMethod.Post))
{
    @Html.HiddenFor(m => m.Id)
    @Html.EditorFor(m => m.Thread)
    @Html.ValidationMessageFor(m => m.Thread)
    @Html.DisplayFor(m => m.Text)
    @Html.ValidationMessageFor(m => m.Id)
    @Html.AntiForgeryToken()
    <input type="submit" value="Delete" />
}

TeamDataForum/TeamDataForum.Web/Views/Shared/EditorTemplates/ThreadBindingModel.cshtml
@using TeamDataForum.Web.Models.BindingModels.Threads
@model ThreadBindingModel

@using (Html.BeginForm("Create", "Thread", FormMethod.Post))
{
    @Html.EditorFor(m => m.Forum)
    @Html.ValidationMessageFor(m => m.Forum)
    @Html.DisplayFor(m => m.Title)
    @Html.EditorFor(m => m.Title)
    @Html.ValidationMessageFor(m => m.Title)
    @Html.DisplayFor(m => m.Text)
    @Html.EditorFor(m => m.Text)
    @Html.ValidationMessageFor(m => m.Text)
    @Html.AntiForgeryToken()
    <input type="submit" value="Create"/>
}

TeamDataForum/TeamDataForum.Web/Views/Shared/EditorTemplates/ThreadPostBindingModel.cshtml
@using TeamDataForum.Web.Models.BindingModels.Posts
@model ThreadPostBindingModel

@using (Html.BeginForm("Create", "Post", FormMethod.Post))
{
    @Html.EditorFor(m => m.Thread)
    @Html.DisplayFor(m => m.Text)
    @Html.EditorFor(m => m.Text)
    @Html.AntiForgeryToken()
    <input type="submit" value="Create" />
}

TeamDataForum/TeamDataForum.Web/Views/Shared/EditorTemplates/UserLogEditorTemplate.cshtml
@using TeamDataForum.Web.Models.BindingModels.Users
@model UserLogBindingModel

<link href="~/Content/Login-style.css" rel="stylesheet" />
<div class="container">
    <div class="card card-container">
        <img id="profile-img" class="profile-img-card" src="//ssl.gstatic.com/accounts/ui/avatar_2x.png" />
        <p id="profile-name" class="profile-name-card"></p>

        @using (Html.BeginForm("SignUp", "Account", FormMethod.Post))
        {
            <span id="reauth-email" class="reauth-email"></span>
            <input type="text" id="Username" class="form-control" placeholder="Username">
            <input type="password" id="Password" class="form-control" placeholder="Password">
            <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>
            <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Register</button>
        }

    </div><!-- /card-container -->
</div><!-- /container -->